"""Initial migration.

Revision ID: 3d87b85a3a09
Revises: 
Create Date: 2022-07-10 14:06:41.218847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d87b85a3a09"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "admins",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("admins", sa.Column("updated_on", sa.DateTime(), nullable=True))
    op.add_column("analysis", sa.Column("updated_on", sa.DateTime(), nullable=True))
    op.add_column(
        "analysts",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("analysts", sa.Column("updated_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysts", "updated_on")
    op.drop_column("analysts", "created_on")
    op.drop_column("analysis", "updated_on")
    op.drop_column("admins", "updated_on")
    op.drop_column("admins", "created_on")
    # ### end Alembic commands ###
