"""Enum fix_2

Revision ID: 3f1f2f5510c6
Revises: 4ec5e4b033cd
Create Date: 2022-08-20 16:16:38.193376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1f2f5510c6'
down_revision = '4ec5e4b033cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('type', sa.Enum('balance_sheet', 'recommendation', 'analysis', name='analysistype'), server_default='analysis', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'type')
    # ### end Alembic commands ###
