"""Analysis Section

Revision ID: 6a4cc7d02007
Revises: 3d87b85a3a09
Create Date: 2022-07-10 15:41:49.845694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4cc7d02007'
down_revision = '3d87b85a3a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('analysis', sa.Column('firm', sa.String(length=100), nullable=False))
    op.add_column('analysis', sa.Column('to_grade', sa.String(length=100), nullable=False))
    op.drop_column('analysis', 'confidence')
    op.drop_column('analysis', 'outcome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('outcome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('analysis', sa.Column('confidence', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('analysis', 'to_grade')
    op.drop_column('analysis', 'firm')
    op.drop_column('analysis', 'date')
    # ### end Alembic commands ###
