"""analysis_model_update

Revision ID: 9f37f26dacff
Revises: 462581f4c702
Create Date: 2022-07-18 19:58:57.978690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9f37f26dacff"
down_revision = "462581f4c702"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis", sa.Column("type", sa.String(length=30), nullable=False))
    op.drop_column("analysis", "firm")
    op.drop_column("analysis", "date")
    op.drop_column("analysis", "to_grade")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis",
        sa.Column(
            "to_grade", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "analysis",
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis",
        sa.Column("firm", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_column("analysis", "type")
    # ### end Alembic commands ###
